spring:
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      uri: localhost
      port: 27017
      database: journalApp
      auto-index-creation: true



weather:
  api:
    key: api_key

