spring:
  redis:
    host: redis-17532.c212.ap-south-1-1.ec2.redns.redis-cloud.com
    port: 17532
    password: admin
  data:
    mongodb:
      uri: mongodb+srv://nk:nk@cluster0.qtllmns.mongodb.net/compossoo
      database: journalApp
      auto-index-creation: true



weather:
  api:
    key: 460fee5185498b3564a6024afcdf9552

